# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from runtime_security_server.grpc_gen import api_pb2 as api__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in runtime_security_server/grpc_gen/api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SecurityModuleEventStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEventStream = channel.unary_stream(
                '/api.SecurityModuleEvent/GetEventStream',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=api__pb2.SecurityEventMessage.FromString,
                _registered_method=True)
        self.GetActivityDumpStream = channel.unary_stream(
                '/api.SecurityModuleEvent/GetActivityDumpStream',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=api__pb2.ActivityDumpStreamMessage.FromString,
                _registered_method=True)


class SecurityModuleEventServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEventStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActivityDumpStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecurityModuleEventServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEventStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetEventStream,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=api__pb2.SecurityEventMessage.SerializeToString,
            ),
            'GetActivityDumpStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetActivityDumpStream,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=api__pb2.ActivityDumpStreamMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.SecurityModuleEvent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.SecurityModuleEvent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SecurityModuleEvent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEventStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/api.SecurityModuleEvent/GetEventStream',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            api__pb2.SecurityEventMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActivityDumpStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/api.SecurityModuleEvent/GetActivityDumpStream',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            api__pb2.ActivityDumpStreamMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SecurityModuleCmdStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DumpProcessCache = channel.unary_unary(
                '/api.SecurityModuleCmd/DumpProcessCache',
                request_serializer=api__pb2.DumpProcessCacheParams.SerializeToString,
                response_deserializer=api__pb2.SecurityDumpProcessCacheMessage.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/api.SecurityModuleCmd/GetConfig',
                request_serializer=api__pb2.GetConfigParams.SerializeToString,
                response_deserializer=api__pb2.SecurityConfigMessage.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/api.SecurityModuleCmd/GetStatus',
                request_serializer=api__pb2.GetStatusParams.SerializeToString,
                response_deserializer=api__pb2.Status.FromString,
                _registered_method=True)
        self.RunSelfTest = channel.unary_unary(
                '/api.SecurityModuleCmd/RunSelfTest',
                request_serializer=api__pb2.RunSelfTestParams.SerializeToString,
                response_deserializer=api__pb2.SecuritySelfTestResultMessage.FromString,
                _registered_method=True)
        self.GetRuleSetReport = channel.unary_unary(
                '/api.SecurityModuleCmd/GetRuleSetReport',
                request_serializer=api__pb2.GetRuleSetReportParams.SerializeToString,
                response_deserializer=api__pb2.GetRuleSetReportMessage.FromString,
                _registered_method=True)
        self.ReloadPolicies = channel.unary_unary(
                '/api.SecurityModuleCmd/ReloadPolicies',
                request_serializer=api__pb2.ReloadPoliciesParams.SerializeToString,
                response_deserializer=api__pb2.ReloadPoliciesResultMessage.FromString,
                _registered_method=True)
        self.DumpNetworkNamespace = channel.unary_unary(
                '/api.SecurityModuleCmd/DumpNetworkNamespace',
                request_serializer=api__pb2.DumpNetworkNamespaceParams.SerializeToString,
                response_deserializer=api__pb2.DumpNetworkNamespaceMessage.FromString,
                _registered_method=True)
        self.DumpDiscarders = channel.unary_unary(
                '/api.SecurityModuleCmd/DumpDiscarders',
                request_serializer=api__pb2.DumpDiscardersParams.SerializeToString,
                response_deserializer=api__pb2.DumpDiscardersMessage.FromString,
                _registered_method=True)
        self.DumpActivity = channel.unary_unary(
                '/api.SecurityModuleCmd/DumpActivity',
                request_serializer=api__pb2.ActivityDumpParams.SerializeToString,
                response_deserializer=api__pb2.ActivityDumpMessage.FromString,
                _registered_method=True)
        self.ListActivityDumps = channel.unary_unary(
                '/api.SecurityModuleCmd/ListActivityDumps',
                request_serializer=api__pb2.ActivityDumpListParams.SerializeToString,
                response_deserializer=api__pb2.ActivityDumpListMessage.FromString,
                _registered_method=True)
        self.StopActivityDump = channel.unary_unary(
                '/api.SecurityModuleCmd/StopActivityDump',
                request_serializer=api__pb2.ActivityDumpStopParams.SerializeToString,
                response_deserializer=api__pb2.ActivityDumpStopMessage.FromString,
                _registered_method=True)
        self.TranscodingRequest = channel.unary_unary(
                '/api.SecurityModuleCmd/TranscodingRequest',
                request_serializer=api__pb2.TranscodingRequestParams.SerializeToString,
                response_deserializer=api__pb2.TranscodingRequestMessage.FromString,
                _registered_method=True)
        self.ListSecurityProfiles = channel.unary_unary(
                '/api.SecurityModuleCmd/ListSecurityProfiles',
                request_serializer=api__pb2.SecurityProfileListParams.SerializeToString,
                response_deserializer=api__pb2.SecurityProfileListMessage.FromString,
                _registered_method=True)
        self.SaveSecurityProfile = channel.unary_unary(
                '/api.SecurityModuleCmd/SaveSecurityProfile',
                request_serializer=api__pb2.SecurityProfileSaveParams.SerializeToString,
                response_deserializer=api__pb2.SecurityProfileSaveMessage.FromString,
                _registered_method=True)


class SecurityModuleCmdServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DumpProcessCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunSelfTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuleSetReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadPolicies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DumpNetworkNamespace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DumpDiscarders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DumpActivity(self, request, context):
        """Activity dumps
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListActivityDumps(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopActivityDump(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TranscodingRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSecurityProfiles(self, request, context):
        """Security Profiles
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveSecurityProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecurityModuleCmdServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DumpProcessCache': grpc.unary_unary_rpc_method_handler(
                    servicer.DumpProcessCache,
                    request_deserializer=api__pb2.DumpProcessCacheParams.FromString,
                    response_serializer=api__pb2.SecurityDumpProcessCacheMessage.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=api__pb2.GetConfigParams.FromString,
                    response_serializer=api__pb2.SecurityConfigMessage.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=api__pb2.GetStatusParams.FromString,
                    response_serializer=api__pb2.Status.SerializeToString,
            ),
            'RunSelfTest': grpc.unary_unary_rpc_method_handler(
                    servicer.RunSelfTest,
                    request_deserializer=api__pb2.RunSelfTestParams.FromString,
                    response_serializer=api__pb2.SecuritySelfTestResultMessage.SerializeToString,
            ),
            'GetRuleSetReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuleSetReport,
                    request_deserializer=api__pb2.GetRuleSetReportParams.FromString,
                    response_serializer=api__pb2.GetRuleSetReportMessage.SerializeToString,
            ),
            'ReloadPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadPolicies,
                    request_deserializer=api__pb2.ReloadPoliciesParams.FromString,
                    response_serializer=api__pb2.ReloadPoliciesResultMessage.SerializeToString,
            ),
            'DumpNetworkNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.DumpNetworkNamespace,
                    request_deserializer=api__pb2.DumpNetworkNamespaceParams.FromString,
                    response_serializer=api__pb2.DumpNetworkNamespaceMessage.SerializeToString,
            ),
            'DumpDiscarders': grpc.unary_unary_rpc_method_handler(
                    servicer.DumpDiscarders,
                    request_deserializer=api__pb2.DumpDiscardersParams.FromString,
                    response_serializer=api__pb2.DumpDiscardersMessage.SerializeToString,
            ),
            'DumpActivity': grpc.unary_unary_rpc_method_handler(
                    servicer.DumpActivity,
                    request_deserializer=api__pb2.ActivityDumpParams.FromString,
                    response_serializer=api__pb2.ActivityDumpMessage.SerializeToString,
            ),
            'ListActivityDumps': grpc.unary_unary_rpc_method_handler(
                    servicer.ListActivityDumps,
                    request_deserializer=api__pb2.ActivityDumpListParams.FromString,
                    response_serializer=api__pb2.ActivityDumpListMessage.SerializeToString,
            ),
            'StopActivityDump': grpc.unary_unary_rpc_method_handler(
                    servicer.StopActivityDump,
                    request_deserializer=api__pb2.ActivityDumpStopParams.FromString,
                    response_serializer=api__pb2.ActivityDumpStopMessage.SerializeToString,
            ),
            'TranscodingRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.TranscodingRequest,
                    request_deserializer=api__pb2.TranscodingRequestParams.FromString,
                    response_serializer=api__pb2.TranscodingRequestMessage.SerializeToString,
            ),
            'ListSecurityProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSecurityProfiles,
                    request_deserializer=api__pb2.SecurityProfileListParams.FromString,
                    response_serializer=api__pb2.SecurityProfileListMessage.SerializeToString,
            ),
            'SaveSecurityProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveSecurityProfile,
                    request_deserializer=api__pb2.SecurityProfileSaveParams.FromString,
                    response_serializer=api__pb2.SecurityProfileSaveMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.SecurityModuleCmd', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.SecurityModuleCmd', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SecurityModuleCmd(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DumpProcessCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SecurityModuleCmd/DumpProcessCache',
            api__pb2.DumpProcessCacheParams.SerializeToString,
            api__pb2.SecurityDumpProcessCacheMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SecurityModuleCmd/GetConfig',
            api__pb2.GetConfigParams.SerializeToString,
            api__pb2.SecurityConfigMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SecurityModuleCmd/GetStatus',
            api__pb2.GetStatusParams.SerializeToString,
            api__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunSelfTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SecurityModuleCmd/RunSelfTest',
            api__pb2.RunSelfTestParams.SerializeToString,
            api__pb2.SecuritySelfTestResultMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuleSetReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SecurityModuleCmd/GetRuleSetReport',
            api__pb2.GetRuleSetReportParams.SerializeToString,
            api__pb2.GetRuleSetReportMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReloadPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SecurityModuleCmd/ReloadPolicies',
            api__pb2.ReloadPoliciesParams.SerializeToString,
            api__pb2.ReloadPoliciesResultMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DumpNetworkNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SecurityModuleCmd/DumpNetworkNamespace',
            api__pb2.DumpNetworkNamespaceParams.SerializeToString,
            api__pb2.DumpNetworkNamespaceMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DumpDiscarders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SecurityModuleCmd/DumpDiscarders',
            api__pb2.DumpDiscardersParams.SerializeToString,
            api__pb2.DumpDiscardersMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DumpActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SecurityModuleCmd/DumpActivity',
            api__pb2.ActivityDumpParams.SerializeToString,
            api__pb2.ActivityDumpMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListActivityDumps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SecurityModuleCmd/ListActivityDumps',
            api__pb2.ActivityDumpListParams.SerializeToString,
            api__pb2.ActivityDumpListMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopActivityDump(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SecurityModuleCmd/StopActivityDump',
            api__pb2.ActivityDumpStopParams.SerializeToString,
            api__pb2.ActivityDumpStopMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TranscodingRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SecurityModuleCmd/TranscodingRequest',
            api__pb2.TranscodingRequestParams.SerializeToString,
            api__pb2.TranscodingRequestMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSecurityProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SecurityModuleCmd/ListSecurityProfiles',
            api__pb2.SecurityProfileListParams.SerializeToString,
            api__pb2.SecurityProfileListMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveSecurityProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SecurityModuleCmd/SaveSecurityProfile',
            api__pb2.SecurityProfileSaveParams.SerializeToString,
            api__pb2.SecurityProfileSaveMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SecurityAgentAPIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendEvent = channel.stream_unary(
                '/api.SecurityAgentAPI/SendEvent',
                request_serializer=api__pb2.SecurityEventMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SendActivityDumpStream = channel.stream_unary(
                '/api.SecurityAgentAPI/SendActivityDumpStream',
                request_serializer=api__pb2.ActivityDumpStreamMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class SecurityAgentAPIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendEvent(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendActivityDumpStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecurityAgentAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendEvent': grpc.stream_unary_rpc_method_handler(
                    servicer.SendEvent,
                    request_deserializer=api__pb2.SecurityEventMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SendActivityDumpStream': grpc.stream_unary_rpc_method_handler(
                    servicer.SendActivityDumpStream,
                    request_deserializer=api__pb2.ActivityDumpStreamMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.SecurityAgentAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.SecurityAgentAPI', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SecurityAgentAPI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendEvent(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/api.SecurityAgentAPI/SendEvent',
            api__pb2.SecurityEventMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendActivityDumpStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/api.SecurityAgentAPI/SendActivityDumpStream',
            api__pb2.ActivityDumpStreamMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
